In [ ]:
#NUMPY
#ndarrray.ndim--eksen boyut sayısı
#ndarrray.shape
#ndarrray.size--toplam eleman sayısı
#ndarrray.dtype--veri tipi
#ndarrray.itemsize--byte cinsinden boyutu
#ndarrray.data-- dizi elemanlarının tümünü verir
#np.arrange--sıralı eleman
#np.linspace--verilen aralıkta sayı üretir
#np.argmin np.argmax --(birinci satiır boyunca dikey olarak aşağıya doğru ikinci sütün boyunca yatay olarak)

In [123]:
import numpy as np

In [125]:
dizi = np.arange(12).reshape(3,4)

In [132]:
print(dizi)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [135]:
dizi.shape

(3, 4)

In [136]:
dizi.dtype

dtype('int32')

In [138]:
dizi.itemsize

4

In [139]:
dizi.ndim

2

In [140]:
dizi.size

12

In [32]:
a=np.array([1,2,3])

In [33]:
b=np.array([[1,2,3],[4,5,6]],dtype='float64') #bu

In [34]:
b=np.array([[1,2,3],[4,5,6]],dtype=np.float64) #veya bu

In [35]:
a.dtype

dtype('int32')

In [36]:
a=np.array([.1,2,3])

In [37]:
a.dtype

dtype('float64')

In [38]:
b.dtype

dtype('float64')

** Numpy dizisi ile oluşturulan bazı fonksiyonlar :  **

In [39]:
a = np.zeros((2,2)) #2*2 lik sıfır matrisi oluşturur

In [40]:
b=np.ones((1,2))  #1*2 lik birim matrisi oluşturur

In [41]:
c=np.full((2,2),7) #sabit sayıdan oluşan 2*2 lik  bir matris oluşturur

In [42]:
d=np.eye(2) #2*2 lik birim matris oluşturur

In [43]:
e=np.random.random((2,2)) #rasgele sayılardan oluşan 2*2 lik birim matris oluşturur

In [45]:
np.linspace(0,50,9)

array([ 0.  ,  6.25, 12.5 , 18.75, 25.  , 31.25, 37.5 , 43.75, 50.  ])

In [142]:
np.linspace(0,50,11)

array([ 0.,  5., 10., 15., 20., 25., 30., 35., 40., 45., 50.])

In [143]:
matrix = np.random.randint(0, 101, size = (10, 10))
print("Orijinal matris.\n", matrix)

Orijinal matris.
 [[  3  36  95  85  44  78  10  73  90  99]
 [ 68  50  71   2  68  92  46  51  45  44]
 [ 93  76  23  99  56   0  73  39  25   3]
 [ 15  36  93  95  98  39  66  26  72   8]
 [ 55  89  66   1  77  61   8 100   8  65]
 [ 11   5  74  21  66   5   5  73  22  22]
 [ 93  38  42  81  35  46  63  26  32  87]
 [ 18  27  49  40   6  44  29  26  61  85]
 [ 88  77  12  93  47  34   0  38  42   8]
 [ 15   8  95  96  53  61  83   3   7   1]]


In [46]:
np.arange(2,10,2)

array([2, 4, 6, 8])

In [141]:
np.arange(20,0,-5)

array([20, 15, 10,  5])

In [47]:
import numpy as np

In [48]:
#first array
arr1 = np.array([[4, 7],[2,6]],
               dtype = np.float64)

In [50]:
#second array
arr2 = np.array([[3,6],[2,8]],
                dtype = np.float64)

In [51]:
#iki arrayi toplama
Sum = np.add(arr1,arr2)
print("Addition of Two Arrays: ")
print(Sum)

Addition of Two Arrays: 
[[ 7. 13.]
 [ 4. 14.]]


In [52]:
#Tüm elemanların toplamı
Sum1 = np.sum(arr1)
print("/nAddition of Array elements: ")
print(Sum1)

/nAddition of Array elements: 
19.0


In [53]:
#Tüm elemanların karekökünü alma
Sqrt = np.sqrt(arr1)
print( "/nSquare root af Array1 elements:")
print(Sqrt)

/nSquare root af Array1 elements:
[[2.         2.64575131]
 [1.41421356 2.44948974]]


In [144]:
#Transpozunu alma 
Trans_arr = arr1.T
print("\nTranspose of Array:  ")
print(Trans_arr)


Transpose of Array:  
[[4. 2.]
 [7. 6.]]


In [64]:
# a=np.arange(10)*2

In [72]:
import numpy as np
a = np.array([[1,2],[3,4],[5,6]])
bool_idx = (a>2) #a nın 2 den büyük elemanları
bool_idx
a[bool_idx]

array([3, 4, 5, 6])

In [73]:
print(a[a > 2])

[3 4 5 6]


In [74]:
#Farklı boyutlardaki Numpy dizileri yatay veya düşey olarak birleştirilebilir:
a = np.array([[2,4,6],[7,1,9]])
b = np.array([[8,3,2],[1,6,0]])
np.vstack((a,b))

array([[2, 4, 6],
       [7, 1, 9],
       [8, 3, 2],
       [1, 6, 0]])

In [75]:
np.hstack((a,b))

array([[2, 4, 6, 8, 3, 2],
       [7, 1, 9, 1, 6, 0]])

In [76]:
#Temel vektör ve matris işlemleri
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

In [77]:
np.add(x,y) #x + y

array([[ 6.,  8.],
       [10., 12.]])

In [78]:
np.subtract(x,y)  #x - y

array([[-4., -4.],
       [-4., -4.]])

In [79]:
np.multiply(x,y)  #x * y

array([[ 5., 12.],
       [21., 32.]])

In [80]:
np.divide(x,y)   #x / y

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [81]:
np.sqrt(x)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [82]:
a=np.random.random((5,5))

In [89]:
##################
matrix = np.random.randint(1, 101, size=(10, 10))
print("orjinal matris: /n ", matrix)

orjinal matris: /n  [[41 70 94 35 16 77 54 21 35  9]
 [40 91 33 92 15 11 45 80 28 84]
 [22 72 86 85 20 92 17 39 78 56]
 [73 64 29 89  6 84  3 96 52 81]
 [ 2 21 94 25 15  6 71 11  4 54]
 [ 3 45 54 67 78 16 22 83 52  4]
 [23 71 51 30 77 84 53 23 71 20]
 [41 45 39  1 54 94 79 66 62 31]
 [25 14 81  2 80  3 87 33 15 41]
 [50 43 55 60 91 96 76 20 81 63]]


In [90]:
print("/n en küçük elemanın indisi : ", np.argmin(arr1, axis=1))
print("/n en büyük elemanın indisi : ", np.argmax(arr1, axis=1))

/n en küçük elemanın indisi :  [0 0]
/n en büyük elemanın indisi :  [1 1]


In [91]:
print("/nDizinin standart sapması: ", np.std(arr1))

/nDizinin standart sapması:  1.920286436967152


In [92]:
print("/n en küçük elemanın indisi : ", np.argmin(arr1))

/n en küçük elemanın indisi :  2


In [93]:
print("/n en büyük elemanın indisi : ", np.argmax(arr1))

/n en büyük elemanın indisi :  1


In [ ]:
################## PANDAS

In [94]:
import pandas as pd

In [95]:
a= pd.Series([5,54,12,22,15,87])
print(a)

0     5
1    54
2    12
3    22
4    15
5    87
dtype: int64


In [96]:
print(a.index)

RangeIndex(start=0, stop=6, step=1)


In [97]:
print(a.values)

[ 5 54 12 22 15 87]


In [98]:
indisler = ['Ali','Mehmet','Ahmet','Veli','Arda','Doruk']
degerler = [5,54,12,22,15,87]
a=pd.Series(degerler,index=indisler)
print(a)

Ali        5
Mehmet    54
Ahmet     12
Veli      22
Arda      15
Doruk     87
dtype: int64


In [99]:
indisler = ['Ali','Mehmet','Ahmet','Veli','Arda','Doruk']
degerler = [5,54,12,22,15,87]
a=pd.Series(degerler,index=indisler)
print(a[['Mehmet','Arda','Ali']])

Mehmet    54
Arda      15
Ali        5
dtype: int64


In [100]:
sonuc=a

In [101]:
indisler = ['Ali','Mehmet','Ahmet','Veli','Arda','Doruk']
degerler = [5,54,12,22,15,87]
a=pd.Series(degerler,index=indisler)
print(5*a+2)
print(np.sqrt(a))

Ali        27
Mehmet    272
Ahmet      62
Veli      112
Arda       77
Doruk     437
dtype: int64
Ali       2.236068
Mehmet    7.348469
Ahmet     3.464102
Veli      4.690416
Arda      3.872983
Doruk     9.327379
dtype: float64


In [103]:
indisler = ['Ali','Mehmet','Ahmet','Veli','Arda','Doruk']
degerler = [5,54,12,22,15,87]
a=pd.Series(degerler,index=indisler)
print(a%2 !=0)
print(np.sqrt(a))  

Ali        True
Mehmet    False
Ahmet     False
Veli      False
Arda       True
Doruk      True
dtype: bool
Ali       2.236068
Mehmet    7.348469
Ahmet     3.464102
Veli      4.690416
Arda      3.872983
Doruk     9.327379
dtype: float64


In [104]:
indisler = ['Ali','Mehmet','Ahmet','Veli','Arda','Doruk']
degerler = [5,54,12,22,15,87]
a=pd.Series(degerler,index=indisler)
print(a[a>50])


Mehmet    54
Doruk     87
dtype: int64


In [120]:
import pandas as pd
ogrenciler = {
    'isim' : ['Ali','Ahmet','Mehmet','Veli','Doruk','Can'],
    'not' : [5,54,12,22,15,87],
    'yas' : [21,24,18,28,20,22]}
a = pd.DataFrame(ogrenciler)
print(a)

     isim  not  yas
0     Ali    5   21
1   Ahmet   54   24
2  Mehmet   12   18
3    Veli   22   28
4   Doruk   15   20
5     Can   87   22


In [121]:
import pandas as pd
ogrenciler = {
    'isim' : ['Ali','Ahmet','Mehmet','Veli','Doruk','Can'],
    'not' : [5,54,12,22,15,87],
    'yas' : [21,24,18,28,20,22]}
a = pd.DataFrame(ogrenciler,columns= {'isim','not','yas','giris'})
print(a)

     isim  not  yas giris
0     Ali    5   21   NaN
1   Ahmet   54   24   NaN
2  Mehmet   12   18   NaN
3    Veli   22   28   NaN
4   Doruk   15   20   NaN
5     Can   87   22   NaN


In [122]:
import pandas as pd
ogrenciler = {
    'isim' : ['Ali','Ahmet','Mehmet','Veli','Doruk','Can'],
    'not' : [5,54,12,22,15,87],
    'yas' : [21,24,18,28,20,22]}
a = pd.DataFrame(ogrenciler)
print(a)
print(a.T)

     isim  not  yas
0     Ali    5   21
1   Ahmet   54   24
2  Mehmet   12   18
3    Veli   22   28
4   Doruk   15   20
5     Can   87   22
        0      1       2     3      4    5
isim  Ali  Ahmet  Mehmet  Veli  Doruk  Can
not     5     54      12    22     15   87
yas    21     24      18    28     20   22
